# Generated by Django 6.0.2 on 2026-02-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('dob', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('class_of_entry', models.CharField(max_length=50)),
                ('home_address', models.TextField()),
                ('state_of_residence', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_relationship', models.CharField(max_length=50)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('guardian_occupation', models.CharField(max_length=100)),
                ('previous_school', models.CharField(max_length=200)),
                ('school_address', models.TextField()),
                ('last_class', models.CharField(max_length=50)),
                ('reason_for_leaving', models.TextField()),
                ('health_issues', models.CharField(max_length=10)),
                ('health_details', models.TextField(blank=True)),
                ('vocational_skill', models.CharField(max_length=100)),
                ('career_aspiration', models.CharField(max_length=100)),
                ('extracurricular', models.CharField(max_length=200)),
                ('how_heard', models.CharField(max_length=200)),
                ('additional_comments', models.TextField(blank=True)),
                ('payment_proof', models.FileField(upload_to='payment_proofs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
