# Generated by Django 6.0.2 on 2026-02-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='additional_comments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='guardian_relationship',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian'), ('Sponsor', 'Sponsor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='health_issues',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='middle_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='vocational_skill',
            field=models.CharField(choices=[('Tailoring', 'Tailoring'), ('Catering', 'Catering'), ('Hair Dressing', 'Hair Dressing'), ('Computer Training', 'Computer Training'), ('Graphic Design', 'Graphic Design'), ('Music', 'Music')], max_length=50),
        ),
    ]
