# Generated by Django 6.0.2 on 2026-03-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_application_additional_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='vocational_skill',
            field=models.CharField(choices=[('BAKING', 'BAKING'), ('CATERING', 'CATERING'), ('INTERLOCK', 'INTERLOCK'), ('BARBING', 'BARBING'), ('HAIRDRESSING', 'HAIRDRESSING'), ('PAINTING', 'PAINTING'), ('ART AND CRAFTS', 'ART AND CRAFTS')], max_length=50),
        ),
    ]
